=== route4me/route4me-nodejs-sdk/test/REMOVE.Address.jsonschema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "https://github.com/route4me/json-schemas/blob/master/Address.dtd",
	"title": "Address",
	"description": "Json schema for an Address response class. See curl examples: get_route_directions, get_route_path_points",
	"type": "object",
	"properties": {
		"route_destination_id": {
			"type": "integer",
			"title": "Route Destination ID",
			"description": "Internal unique address identifier"
		},
		"alias": {
			"type": "string",
			"title": "Address Alias",
			"description": "Address Alias"
		},
		"member_id": {
			"type": "integer",
			"title": "Member ID",
			"description": "Member ID"
		},
		"address": {
			"type": "string",
			"title": "Address Name",
			"description": "The route Address Line 1"
		},
		"is_depot": {
			"type": "boolean",
			"title": "Is Depot",
			"description": "This address is a depot",
			"default": "false"
		},
		"timeframe_violation_state": {
			"type": "integer",
			"title": "Timeframe violation state",
			"description": "State of the timeframe violation. In a response only"
		},
		"timeframe_violation_time": {
			"type": "integer",
			"title": "Timeframe violation time",
			"description": "Moment of the timeframe violation. In a response only"
		},
		"timeframe_violation_rate": {
			"type": "number",
			"title": "Timeframe violation rate",
			"description": "Rate of the timeframe violation. In a response only"
		},
		"lat": {
			"type": "number",
			"title": "Latitude",
			"description": "Latitude",
			"minimum": -90,
			"maximum": 90
		},
		"lng": {
			"type": "number",
			"title": "Longitude",
			"description": "Longitude",
			"minimum": -180,
			"maximum": 180
		},
		"curbside_lat": {
			"type": "number",
			"title": "Curbside Latitude",
			"description": "Curbside latitude",
			"minimum": -90,
			"maximum": 90
		},
		"curbside_lng": {
			"type": "number",
			"title": "Curbside Longitude",
			"description": "Curbside longitude",
			"minimum": -180,
			"maximum": 180
		},
		"priority": {
			"type": "integer",
			"title": "Priority",
			"description": "0 is the highest priority; n has higher priority than n + 1"
		},
		"route_id": {
			"type": "string",
			"title": "Route ID",
			"description": "Parent route"
		},
		"original_route_id": {
			"type": "string",
			"title": "Original Route ID",
			"description": "The original customer-specific route id assigned at route creation time."
		},
		"route_name": {
			"type": "string",
			"title": "Route Name",
			"description": "Route Name"
		},
		"optimization_problem_id": {
			"type": "string",
			"title": "Optimization Problem ID",
			"description": "Optimization Problem ID"
		},
		"sequence_no": {
			"type": "integer",
			"title": "Sequence No",
			"description": "The sequence number for the address"
		},
		"geocoded": {
			"type": "boolean",
			"title": "Geocoded",
			"description": "True means the 'address' field was successfully geocoded"
		},
		"preferred_geocoding": {
			"type": "integer",
			"title": "Preferred Geocoding",
			"description": "Index of 'geocodings' array that the user has chosen"
		},
		"failed_geocoding": {
			"type": "boolean",
			"title": "Failed Geocoding",
			"description": "True means there was a geocoding attempt which failed. False means success or no geocoding"
		},
		"geocodings": {
			"type": "array",
			"items": {"$ref": "https://github.com/route4me/json-schemas/blob/master/geocoding.dtd"},
			"title": "Geocodings ID"
		},
		"contact_id": {
			"type": "integer",
			"minimum": 0,
			"title": "Contact ID",
			"description": "Address book contact id (0 means not connected to the address book)"
		},
		"order_id": {
			"type": "integer",
			"title": "Order ID",
			"description": "Parent order ID"
		},
		"address_stop_type": {
			"type": "string",
			"enum": ["PICKUP", "DELIVERY", "BREAK", "MEETUP"],
			"title": "Address stop type",
			"description": "The type of stop that this is (PICKUP, DELIVERY, BREAK, MEETUP)"
		},
		"is_visited": {
			"type": "boolean",
			"title": "Is Visited",
			"description": "The driver pressed the 'Visited' button",
			"default": "false"
		},
		"timestamp_last_visited": {
			"type": "integer",
			"title": "Timestamp Last Vsited",
			"description": "Timestamp when the driver presses 'Visited'"
		},
		"visited_lat": {
			"type": "number",
			"title": "Visited Latitude",
			"description": "Last known check in latitude",
			"minimum": -90,
			"maximum": 90
		},
		"visited_lng": {
			"type": "number",
			"title": "Visited Longitude",
			"description": "Last known check in longitude",
			"minimum": -180,
			"maximum": 180
		},
		"is_departed": {
			"type": "boolean",
			"title": "Is Departed",
			"description": "The driver marked the 'Departed' button"
		},
		"departed_lat": {
			"type": "number",
			"title": "Departed Latitude",
			"description": "Last known departed latitude",
			"minimum": -90,
			"maximum": 90
		},
		"departed_lng": {
			"type": "number",
			"description": "Last known departed longitude",
			"title": "Departed Longitude",
			"minimum": -180,
			"maximum": 180
		},
		"timestamp_last_departed": {
			"type": "integer",
			"title": "Timestamp Last Departed",
			"description": "Timestamp when the driver marks the stop as 'Departed'"
		},
		"group": {
			"type": "string",
			"title": "Group",
			"description": "Address group"
		},
		"customer_po": {
			"type": "string",
			"title": "Customer PO",
			"description": "The customer purchase order for the address"
		},
		"invoice_no": {
			"type": "string",
			"title": "Invoice No",
			"description": "The invoice number for the address"
		},
		"reference_no": {
			"type": "string",
			"title": "Reference NO",
			"description": "The reference number for the address"
		},
		"order_no": {
			"type": "string",
			"title": "Order NO",
			"description": "The order number for the address"
		},
		"weight": {
			"type": "number",
			"title": "Weight",
			"description": "Weight"
		},
		"cost": {
			"type": "number",
			"title": "Cost",
			"description": "The cost of the order for the address"
		},
		"revenue": {
			"type": "number",
			"title": "Revenue",
			"description": "The total revenue for the address"
		},
		"cube": {
			"type": "number",
			"title": "Cube",
			"description": "The cubic volume of the cargo being delivered or picked up at the address"
		},
		"pieces": {
			"type": "integer",
			"title": "Pieces",
			"description": "Pieces"
		},
		"first_name": {
			"type": "string",
			"title": "First name",
			"description": "The first name of the receiving address"
		},
		"last_name": {
			"type": "string",
			"title": "Last name",
			"description": "The last name of the receiving address"
		},
		"email": {
			"type": "string",
			"format": "email",
			"title": "Email",
			"description": "A valid e-mail address assigned to this stop"
		},
		"phone": {
			"type": "string",
			"title": "Phone",
			"description": "Customer Phone"
		},
		"destination_note_count": {
			"type": "integer",
			"title": "Destination Note Count",
			"description": "How many notes have been added to this destination"
		},
		"drive_time_to_next_destination": {
			"type": "integer",
			"title": "Drive Time to next Destination",
			"description": "Time to next destination in seconds."
		},
		"abnormal_traffic_time_to_next_destination": {
			"type": "integer",
			"description": "Abnormal traffic time to next destination",
			"title": "Abnormal traffic time to next destination"
		},
		"uncongested_time_to_next_destination": {
			"type": "integer",
			"title": "Uncongested Time To Next Destination",
			"description": "Supposing that there was no traffic at all, this gives how many seconds it takes to get to the next stop."
		},
		"traffic_time_to_next_destination": {
			"type": "integer",
			"title": "Traffic Time To Next Destination",
			"description": "Traffic time to a next destination."
		},
		"distance_to_next_destination": {
			"type": "number",
			"title": "Distance to next destination",
			"description": "Distance to next destination in route unit (the default unit is in miles)"
		},
		"channel_name": {
			"type": "string",
			"title": "Channel name",
			"description": "Channel name"
		},
		"generated_time_window_start": {
			"type": "integer",
			"title": "Generated Time Window Start",
			"description": "Generated Time Window Start in seconds"
		},
		"generated_time_window_end": {
			"type": "integer",
			"title": "Generated Time Window End",
			"description": "Generated Time Window End in seconds"
		},
		"time_window_start": {
			"type": "integer",
			"title": "Time Window Start",
			"description": "Time Window Start in seconds, relative to the route start date (midnight), UTC time zone. It is relative to start datebecause start time changes would shift time windows"
		},
		"time_window_end": {
			"type": "integer",
			"title": "Time Window End",
			"description": "Time Window End in seconds, relative to the route start date (midnight), UTC time zone. It is relative to start datebecause start time changes would shift time windows"
		},
		"time_window_start_2": {
			"type": "integer",
			"title": "Time Window Start 2",
			"description": "See time_window_start"
		},
		"time_window_end_2": {
			"type": "integer",
			"title": "Time Window End 2",
			"description": "See time_window_end"
		},
		"geofence_detected_visited_timestamp": {
			"type": "integer",
			"title": "Geofence detected visited timestamp",
			"description": "Timestamp of a geofence detected visited"
		},
		"geofence_detected_departed_timestamp": {
			"type": "integer",
			"title": "Geofence detected departed timestamp",
			"description": "Timestamp of a geofence detected departed"
		},
		"geofence_detected_service_time": {
			"type": "integer",
			"title": "Geofence detected service time",
			"description": "The service time of a detected geofence"
		},
		"geofence_detected_visited_lat": {
			"type": "number",
			"title": "Geofence detected visited lat",
			"description": "Latitude of a visited detected geofence",
			"minimum": -90,
			"maximum": 90
		},
		"geofence_detected_visited_lng": {
			"type": "number",
			"title": "Geofence detected visited lng",
			"description": "Longitude of a visited detected geofence",
			"minimum": -180,
			"maximum": 180
		},
		"geofence_detected_departed_lat": {
			"type": "number",
			"title": "Geofence detected departed lat",
			"description": "Latitude of a departed detected geofence",
			"minimum": -90,
			"maximum": 90
		},
		"geofence_detected_departed_lng": {
			"type": "number",
			"title": "Geofence detected departed lng",
			"description": "Longitude of a departed detected geofence",
			"minimum": -180,
			"maximum": 180
		},
		"time": {
			"type": "integer",
			"title": "Time",
			"description": "Service time (seconds)"
		},
		"tracking_number": {
			"type": "string",
			"title": "Tracking Number",
			"description": "Systemwide unique code, which permits end-users (recipients) to track the status of their order"
		},
		"custom_fields": {
			"type": "array",
			"items": {"type": "string"},
			"description": "Any unrecognized fields from the original CSV upload will be found here",
			"title": "Custom Fields"
		},
		"custom_fields_str_json": {
			"type": "string",
			"title": "Custom fields JSON string",
			"description": "JSON string representation of the custom fields"
		},
		"custom_fields_config": {
			"type": "array",
			"items": {"type": "string"},
			"title": "Custom fields configuration",
			"description": "Configuration of the custom fields"
		},
		"custom_fields_config_str_json": {
			"type": "string",
			"title": "Custom fields config JSON string",
			"description": "JSON string representation of the custom fields configuration"
		},
		"notes": {
			"type": "array",
			"items": {"$ref": "https://github.com/route4me/json-schemas/blob/master/note.dtd"},
			"title": "Notes",
			"description": "Notes"
		},
		"path_to_next": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"lat": {
						"type": "number",
						"title": "Latitude",
						"description": "Latitude",
						"minimum": -90,
						"maximum": 90
					},
					"lng": {
						"type": "number",
						"title": "Longitude",
						"description": "Longitude",
						"minimum": -180,
						"maximum": 180
					}
				}
			}
		},
		"account_no": {
			"type": "string",
			"title": "Account NO",
			"description": "The account number for the address"
		},
		"wait_time_to_next_destination": {
			"type": "integer",
			"title": "Wait time to next destination",
			"description": "Wait time to next destination"
		},
		"manifest": {
			"type": "object",
			"properties": {
				"running_service_time": {
					"type": "integer",
					"title": "Running Service Time",
					"description": "How much time is to be spent on service from the start in seconds"
				},
				"running_travel_time": {
					"type": "integer",
					"title": "Running Travel Time",
					"description": "How much time is spent driving from the start in seconds"
				},
				"running_wait_time": {
					"type": "integer",
					"title": "Running Wait Time",
					"description": "Running Wait Time"
				},
				"running_distance": {
					"type": "number",
					"title": "Running Distance",
					"description": "Distance traversed before reaching this address"
				},
				"fuel_from_start": {
					"type": "number",
					"title": "Fuel From Start",
					"description": "Fuel From Start"
				},
				"fuel_cost_from_start": {
					"type": "number",
					"title": "Fuel Cost From Start",
					"description": "Fuel Cost From Start"
				},
				"projected_arrival_time_ts": {
					"type": "integer",
					"title": "Projected Arrival Time ts",
					"description": "Projected arrival time UTC unixtime"
				},
				"projected_departure_time_ts": {
					"type": "integer",
					"title": "Projected Departure Time ts",
					"description": "Estimated departure time UTC unixtime"
				},
				"actual_arrival_time_ts": {
					"type": "integer",
					"title": "Actual Arrival Time ts",
					"description": "Time when the address was marked as visited UTC unixtime. This is actually equal to timestamp_last_visited most of the time."
				},
				"actual_departure_time_ts": {
					"type": "integer",
					"title": "Actual Departure Time ts",
					"description": "Time when the address was mared as departed UTC. This is actually equal to timestamp_last_departed most of the time."
				},
				"estimated_arrival_time_ts": {
					"type": "integer",
					"title": "Estimated Arrival Time ts",
					"description": "Estimated arrival time based on the current route progress, i.e. based on the last known actual_arrival_time"
				},
				"estimated_departure_time_ts": {
					"type": "integer",
					"title": "Estimated Departure Time ts",
					"description": "Estimated departure time based on the current route progress"
				},
				"time_impact": {
					"type": "integer",
					"title": "Time Impact",
					"description": "This is the difference between the originally projected arrival time and Actual Arrival Time"
				}
			},
			"description": "The manifest contains values derived from other values",
			"title": "Manifest"
		},
		"directions": {
			"type": "array",
			"items": {
				"$ref": "https://github.com/route4me/json-schemas/blob/master/Direction.dtd"
			}
		}
	}
}

=== route4me/route4me-nodejs-sdk/examples/old/addresses.json
[
  {
    "lng": -85.757308,
    "lat": 38.251698,
    "is_depot": true,
    "time": 300,
    "sequence_no": 0,
    "address": "455 S 4th St, Louisville, KY 40202"
  },
  {
    "lng": -85.793846,
    "lat": 38.141598,
    "is_depot": false,
    "time": 300,
    "sequence_no": 1,
    "address": "1604 PARKRIDGE PKWY, Louisville, KY, 40214"
  },
  {
    "lng": -85.786514,
    "lat": 38.202496,
    "is_depot": false,
    "time": 300,
    "sequence_no": 2,
    "address": "1407 MCCOY, Louisville, KY, 40215"
  },
  {
    "lng": -85.774864,
    "lat": 38.178844,
    "is_depot": false,
    "time": 300,
    "sequence_no": 3,
    "address": "4805 BELLEVUE AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.821121,
    "lat": 38.248684,
    "is_depot": false,
    "time": 300,
    "sequence_no": 4,
    "address": "730 CECIL AVENUE, Louisville, KY, 40211"
  },
  {
    "lng": -85.800034,
    "lat": 38.251923,
    "is_depot": false,
    "time": 300,
    "sequence_no": 5,
    "address": "650 SOUTH 29TH ST UNIT 315, Louisville, KY, 40211"
  },
  {
    "lng": -85.824638,
    "lat": 38.176067,
    "is_depot": false,
    "time": 300,
    "sequence_no": 6,
    "address": "4629 HILLSIDE DRIVE, Louisville, KY, 40216"
  },
  {
    "lng": -85.775558,
    "lat": 38.179806,
    "is_depot": false,
    "time": 300,
    "sequence_no": 7,
    "address": "4738 BELLEVUE AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.815094,
    "lat": 38.259335,
    "is_depot": false,
    "time": 300,
    "sequence_no": 8,
    "address": "318 SO. 39TH STREET, Louisville, KY, 40212"
  },
  {
    "lng": -85.785118,
    "lat": 38.179253,
    "is_depot": false,
    "time": 300,
    "sequence_no": 9,
    "address": "1324 BLUEGRASS AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.792854,
    "lat": 38.162472,
    "is_depot": false,
    "time": 300,
    "sequence_no": 10,
    "address": "7305 ROYAL WOODS DR, Louisville, KY, 40214"
  },
  {
    "lng": -85.783966,
    "lat": 38.229584,
    "is_depot": false,
    "time": 300,
    "sequence_no": 11,
    "address": "1661 W HILL ST, Louisville, KY, 40210"
  },
  {
    "lng": -85.822594,
    "lat": 38.210606,
    "is_depot": false,
    "time": 300,
    "sequence_no": 12,
    "address": "3222 KINGSWOOD WAY, Louisville, KY, 40216"
  },
  {
    "lng": -85.796783,
    "lat": 38.153767,
    "is_depot": false,
    "time": 300,
    "sequence_no": 13,
    "address": "1922 PALATKA RD, Louisville, KY, 40214"
  },
  {
    "lng": -85.796852,
    "lat": 38.235847,
    "is_depot": false,
    "time": 300,
    "sequence_no": 14,
    "address": "1314 SOUTH 26TH STREET, Louisville, KY, 40210"
  },
  {
    "lng": -85.789032,
    "lat": 38.218662,
    "is_depot": false,
    "time": 300,
    "sequence_no": 15,
    "address": "2135 MCCLOSKEY AVENUE, Louisville, KY, 40210"
  },
  {
    "lng": -85.781387,
    "lat": 38.206154,
    "is_depot": false,
    "time": 300,
    "sequence_no": 16,
    "address": "1409 PHYLLIS AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.839149,
    "lat": 38.187511,
    "is_depot": false,
    "time": 300,
    "sequence_no": 17,
    "address": "4504 SUNFLOWER AVE, Louisville, KY, 40216"
  },
  {
    "lng": -85.795059,
    "lat": 38.241405,
    "is_depot": false,
    "time": 300,
    "sequence_no": 18,
    "address": "2512 GREENWOOD AVE, Louisville, KY, 40210"
  },
  {
    "lng": -85.863319,
    "lat": 38.166065,
    "is_depot": false,
    "time": 300,
    "sequence_no": 19,
    "address": "5500 WILKE FARM AVE, Louisville, KY, 40216"
  },
  {
    "lng": -85.786201,
    "lat": 38.193283,
    "is_depot": false,
    "time": 300,
    "sequence_no": 20,
    "address": "3640 LENTZ AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.780037,
    "lat": 38.17952,
    "is_depot": false,
    "time": 300,
    "sequence_no": 21,
    "address": "1020 BLUEGRASS AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.814156,
    "lat": 38.26498,
    "is_depot": false,
    "time": 300,
    "sequence_no": 22,
    "address": "123 NORTH 40TH ST, Louisville, KY, 40212"
  },
  {
    "lng": -85.802867,
    "lat": 38.151072,
    "is_depot": false,
    "time": 300,
    "sequence_no": 23,
    "address": "7315 ST ANDREWS WOODS CIRCLE UNIT 104, Louisville, KY, 40214"
  },
  {
    "lng": -85.849937,
    "lat": 38.182594,
    "is_depot": false,
    "time": 300,
    "sequence_no": 24,
    "address": "3210 POPLAR VIEW DR, Louisville, KY, 40216"
  },
  {
    "lng": -85.811447,
    "lat": 38.1754,
    "is_depot": false,
    "time": 300,
    "sequence_no": 25,
    "address": "4519 LOUANE WAY, Louisville, KY, 40216"
  },
  {
    "lng": -85.798279,
    "lat": 38.161839,
    "is_depot": false,
    "time": 300,
    "sequence_no": 26,
    "address": "6812 MANSLICK RD, Louisville, KY, 40214"
  },
  {
    "lng": -85.788353,
    "lat": 38.172031,
    "is_depot": false,
    "time": 300,
    "sequence_no": 27,
    "address": "1524 HUNTOON AVENUE, Louisville, KY, 40215"
  },
  {
    "lng": -85.779816,
    "lat": 38.209663,
    "is_depot": false,
    "time": 300,
    "sequence_no": 28,
    "address": "1307 LARCHMONT AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.791962,
    "lat": 38.26844,
    "is_depot": false,
    "time": 300,
    "sequence_no": 29,
    "address": "434 N 26TH STREET #2, Louisville, KY, 40212"
  },
  {
    "lng": -85.80629,
    "lat": 38.250397,
    "is_depot": false,
    "time": 300,
    "sequence_no": 30,
    "address": "678 WESTLAWN ST, Louisville, KY, 40211"
  },
  {
    "lng": -85.790421,
    "lat": 38.248882,
    "is_depot": false,
    "time": 300,
    "sequence_no": 31,
    "address": "2308 W BROADWAY, Louisville, KY, 40211"
  },
  {
    "lng": -85.794257,
    "lat": 38.233579,
    "is_depot": false,
    "time": 300,
    "sequence_no": 32,
    "address": "2332 WOODLAND AVE, Louisville, KY, 40210"
  },
  {
    "lng": -85.783928,
    "lat": 38.239697,
    "is_depot": false,
    "time": 300,
    "sequence_no": 33,
    "address": "1706 WEST ST. CATHERINE, Louisville, KY, 40210"
  },
  {
    "lng": -85.792397,
    "lat": 38.216465,
    "is_depot": false,
    "time": 300,
    "sequence_no": 34,
    "address": "1699 WATHEN LN, Louisville, KY, 40216"
  },
  {
    "lng": -85.831787,
    "lat": 38.186245,
    "is_depot": false,
    "time": 300,
    "sequence_no": 35,
    "address": "2416 SUNSHINE WAY, Louisville, KY, 40216"
  },
  {
    "lng": -85.798355,
    "lat": 38.158466,
    "is_depot": false,
    "time": 300,
    "sequence_no": 36,
    "address": "6925 MANSLICK RD, Louisville, KY, 40214"
  },
  {
    "lng": -85.785082,
    "lat": 38.212438,
    "is_depot": false,
    "time": 300,
    "sequence_no": 37,
    "address": "2707 7TH ST, Louisville, KY, 40215"
  },
  {
    "lng": -85.826668,
    "lat": 38.179394,
    "is_depot": false,
    "time": 300,
    "sequence_no": 38,
    "address": "2014 KENDALL LN, Louisville, KY, 40216"
  },
  {
    "lng": -85.812012,
    "lat": 38.273354,
    "is_depot": false,
    "time": 300,
    "sequence_no": 39,
    "address": "612 N 39TH ST, Louisville, KY, 40212"
  },
  {
    "lng": -85.786781,
    "lat": 38.261703,
    "is_depot": false,
    "time": 300,
    "sequence_no": 40,
    "address": "2215 ROWAN ST, Louisville, KY, 40212"
  },
  {
    "lng": -85.78653,
    "lat": 38.241611,
    "is_depot": false,
    "time": 300,
    "sequence_no": 41,
    "address": "1826 W. KENTUCKY ST, Louisville, KY, 40210"
  },
  {
    "lng": -85.796211,
    "lat": 38.224716,
    "is_depot": false,
    "time": 300,
    "sequence_no": 42,
    "address": "1810 GREGG AVE, Louisville, KY, 40210"
  },
  {
    "lng": -85.825836,
    "lat": 38.191753,
    "is_depot": false,
    "time": 300,
    "sequence_no": 43,
    "address": "4103 BURRRELL DRIVE, Louisville, KY, 40216"
  },
  {
    "lng": -85.823463,
    "lat": 38.259903,
    "is_depot": false,
    "time": 300,
    "sequence_no": 44,
    "address": "359 SOUTHWESTERN PKWY, Louisville, KY, 40212"
  },
  {
    "lng": -85.792109,
    "lat": 38.252781,
    "is_depot": false,
    "time": 300,
    "sequence_no": 45,
    "address": "2407 W CHESTNUT ST, Louisville, KY, 40211"
  },
  {
    "lng": -85.786658,
    "lat": 38.257616,
    "is_depot": false,
    "time": 300,
    "sequence_no": 46,
    "address": "225 S 22ND ST, Louisville, KY, 40212"
  },
  {
    "lng": -85.786072,
    "lat": 38.202122,
    "is_depot": false,
    "time": 300,
    "sequence_no": 47,
    "address": "1404 MCCOY AVE, Louisville, KY, 40215"
  },
  {
    "lng": -85.799438,
    "lat": 38.270061,
    "is_depot": false,
    "time": 300,
    "sequence_no": 48,
    "address": "117 FOUNT LANDING CT, Louisville, KY, 40212"
  },
  {
    "lng": -85.7798,
    "lat": 38.145851,
    "is_depot": false,
    "time": 300,
    "sequence_no": 49,
    "address": "5504 SHOREWOOD DRIVE, Louisville, KY, 40214"
  },
  {
    "lng": -85.780251,
    "lat": 38.211025,
    "is_depot": false,
    "time": 300,
    "sequence_no": 50,
    "address": "1406 CENTRAL AVE, Louisville, KY, 40208"
  }
]
